{
 "title": "LegoModel",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Wind Energy",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatt", "label": "Power" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  p\nFROM etenergyconsumer\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  maxeolicpowergenerated\nFROM etgreenenergygenerator\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Dokk1",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  availablespotnumber,\n  occupiedspotnumber\nFROM etoffstreetparking\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  temperature\nFROM etweatherobserved\nORDER BY 1,2"
    }
   ]
  }
 ]
}